remoteController:
    resource:   "@xrowbootstrapBundle/Controller/RemoteController.php"
    type:       annotation

test_html:
    path:   test/html
    defaults:  { _controller: xrowbootstrapBundle:Page:index }

test_bootstrap:
    path:   test/bootstrap
    defaults:  { _controller: xrowbootstrapBundle:Page:bootstrap }