_xrowbootstrapBundle_rest:
    resource: "@xrowbootstrapBundle/Resources/config/routing_rest.yml"
    prefix:   %ezpublish_rest.path_prefix%
_xrowbootstrapBundle_test_html:
    path:   test/html
    defaults:  { _controller: xrowbootstrapBundle:Page:index }

_xrowbootstrapBundle_test_bootstrap:
    path:   test/bootstrap
    defaults:  { _controller: xrowbootstrapBundle:Page:bootstrap }

remoteController:
    resource:   "@xrowbootstrapBundle/Controller/RemoteController.php"
    type:       annotation