#    xrowbootstrap.example:
#        class: xrow\bootstrapBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
services:
    xrow.menu.builder:
        class: xrow\bootstrapBundle\Menu\Builder
        arguments:
            - @knp_menu.factory
            - @ezpublish.api.service.search
            - @router
            - @ezpublish.config.resolver
            - @ezpublish.api.service.location
            - @ezpublish.translation_helper
            - @service_container
    xrow.menu.top:
        class: xrow\bootstrapBundle\Menu\Builder
        factory_service: xrow.menu.builder
        factory_method: createTopMenu
        arguments: [ @request ]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: top } # The alias is what is used to retrieve the menu

    xrow.helper.content:
        class: xrow\bootstrapBundle\Helper\Content
        arguments:
            - @ezpublish.api.repository
            - @ezpublish.config.resolver
    xrow.helper.locationUtilities:
        class: xrow\bootstrapBundle\Helper\LocationUtilities
    xrow.configuration_mapper:
        class: xrow\bootstrapBundle\LegacyMapper\AdditionalConfig
        arguments:
            - @ezpublish.config.resolver.core
            - @ezpublish.http_cache.purger
            - @ezpublish_legacy.persistence_cache_purger
            - @ezpublish.urlalias_generator
            - @ezpublish.api.storage_engine.legacy.dbhandler
            - @ezpublish_legacy.image_alias.cleaner
            - %ezpublish_legacy.configuration_mapper.options%
        calls:
            - [setContainer, [@service_container]]
        tags:
            - { name: kernel.event_subscriber }

    xrow.requestresponse:
        class: xrow\bootstrapBundle\EventListener\DBAConnectionListener
        arguments: [@service_container, @logger]
        tags:
         - { name: kernel.event_listener, event: console.command, method: onConsoleCommand }
#         - { name: kernel.event_listener, event: console.terminate, method: onConsoleTerminate }
    Xrow.RestBundle.ValueObjectVisitor.Menu:
        parent: ezpublish_rest.output.value_object_visitor.base
        class: xrow\bootstrapBundle\ValueObjectVisitor\RestMenu
        arguments:
            - @ezpublish.api.service.url_alias
            - @ezpublish.api.service.location
            - @xrow.helper.locationUtilities
            - @ezpublish.api.service.search
        tags:
            - { name: ezpublish_rest.output.value_object_visitor, type: xrow\bootstrapBundle\Values\RestMenu }
