#    xrowbootstrap.example:
#        class: xrow\bootstrapBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
services:
    xrow.menu.builder:
        class: xrow\bootstrapBundle\Menu\Builder
        arguments:
            - @knp_menu.factory
            - @ezpublish.api.service.search
            - @router
            - @ezpublish.config.resolver
            - @ezpublish.api.service.location
            - @ezpublish.translation_helper
            - @service_container
    xrow.menu.top:
        class: xrow\bootstrapBundle\Menu\Builder
        factory_service: xrow.menu.builder
        factory_method: createTopMenu
        arguments: [ @request ]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: top } # The alias is what is used to retrieve the menu